# TODO: Combine data of miltonjohn, johnmilton;
# brownthomas, thomasbrown; popealexander, alexanderpope

QUICK_LOOKUP_AUTHORS_WORKS_JSONS = {
    "Shakesp.": "shakespeare.json",
    "Dryden.": "dryden.json",
    "Shakespeare.": None,
    "Bible": None,
    "Milton.": None,
    "Pope.": None,
    "Locke.": None,
    "Swift.": None,
    "Shakespeare's": None,
    "Bacon.": None,
    "Dryden's": None,
    "Bacon's": None,
    "Addison.": None,
    "Milton's": None,
    "Hooker.": None,
    "Prior.": None,
    "Spenser.": None,
    "Addison's": None,
    "South.": None,
    "Brown's": None,
    "Shak.": None,
    "Sidney.": None,
    "L'Estrange.": None,
    "Dryd.": None,
    "Boyle.": None,
    "Pope's": None,
    "Arbuthnot": None,
    "Shakes.": None,
    "Arbuthnot.": None,
    "South's": None,
    "Waller.": None,
    "Clarendon.": None,
    "Brown.": None,
    "Denham.": None,
    "\"Hooker,\"": None,
    "Atterbury.": None,
    "Temple.": None,
    "Watts.": None,
    "Addison": None,
    "Donne.": None,
    "Tillotson.": None,
    "Wotton.": None,
    "Mortimer's": None,
    "Woodward.": None,
    "Watts's": None,
    "Ray": None,
    "Milt.": None,
    "Hayward.": None,
    "Bentley.": None,
    "Swift's": None
}
